apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: supreecha2003/minikube:1.8
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgres-flask"    # ✅ ใช้ชื่อ service ใหม่
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "mydb"
        - name: DB_USER
          value: "user"
        - name: DB_PASS
          value: "pass"
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-service
spec:
  type: NodePort
  selector:
    app: myweb
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
